version: 2.1
commands:
  commoncmd:
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
jobs:
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - run: sudo apt update
      - run: sudo apt install -qq shellcheck
      - commoncmd
      - run: bash -c './ci/lint.sh'
  unit:
    docker:
      - image: circleci/node:latest
    steps:
      - commoncmd
      - run: bash -c './ci/unit.sh'
  mozilla:
    docker:
      - image: circleci/node:latest
    steps:
      - commoncmd
      - run: bash -c 'ci/mozilla.sh'

workflows:
  version: 2
  build_test_lint:
    jobs:
      - lint
      - mozilla
      - unit
